version: '3.8'
services:
  mysqlserver:
    container_name: mysql
    restart: always
    image: mysql:8.0.33
    environment:
      MYSQL_ROOT_PASSWORD: asdf
      MYSQL_DATABASE: db_api
      MYSQL_USER: seiya
      MYSQL_PASSWORD: asdf
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - '3306:3306'
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
    deploy:
      resources:
        limits:
          cpus: '0.77'
          memory: 240MB
  nginx:
    container_name: load_balancer
    restart: always
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: '0.13'
          memory: 10MB
  api01:
    container_name: api01
    restart: always
    build:
      context: .
    ports:
      - "8081:8081"
    environment:
      - SERVER_PORT=8081
      - MYSQL_URL=jdbc:mysql://mysqlserver/db_api
    volumes:
      - ./:/app
    depends_on:
      - mysqlserver
    healthcheck:
      test: ["CMD", "curl", "-f", "http://mysqlserver:3306"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 150MB
  api02:
    container_name: api02
    restart: always
    build:
      context: .
    ports:
      - "8082:8082"
    environment:
      - SERVER_PORT=8082
      - MYSQL_URL=jdbc:mysql://mysqlserver/db_api
    volumes:
      - ./:/app
    depends_on:
      - mysqlserver
    healthcheck:
      test: ["CMD", "curl", "-f", "http://mysqlserver:3306"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 150MB